version: '3.8'

services:
  postgres:
    build: .
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"

volumes:
  db-data: {}